services:
  # 1. Ini Aplikasi Laravel Kamu
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kasio
    container_name: kasio-app
    restart: unless-stopped
    ports:
      - "8081:80" # Akses di browser via localhost:8081
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db # Perhatikan ini! Kita panggil nama servicenya 'db'
      DB_PORT: 3306
      DB_DATABASE: kasio
      DB_USERNAME: kasio_user
      DB_PASSWORD: password123
    depends_on:
      - db
    networks:
      - kasio-network

  # 2. Ini Database MySQL (Pengganti XAMPP)
  db:
    image: mysql:8.0
    container_name: kasio-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kasio
      MYSQL_USER: kasio_user
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql # Supaya data tidak hilang saat docker dimatikan
    networks:
      - kasio-network

volumes:
  db_data:

networks:
  kasio-network:
    driver: bridge