name: Deploy kasio 

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          
      - run: composer install --no-dev --optimize-autoloader
        
      - uses: azure/webapps-deploy@v3
        with:
          app-name: 'kasio'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_KASIO }}
          package: .  # Folder langsung!
